spring:
  mail:
    host: smtp.gmail.com
    username: Phamthanhhuy3062k3@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    password: dxuauqulylqcqwsn
  datasource:
    password: root
    username: root
    url: jdbc:mysql://mysql-container:3306/fashion
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
minio:
  bucket: fashion
  secretKey: minioadmin
  url: http://localhost:9000
  accessKey: minioadmin
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    enabled: true
server:
  port: 8888
jwt:
  secretKey: 28ABC129DDCFFAHS2310A1232312AABASCSD28ABC129DDCFFAHS2310A1232312AABASCSD28ABC1ABCNSDKAOWUQA12312
